### ISSUE TITLE
关于高级景深ADOF和去除色带Deband

### ISSUE THREAD

**Issue by sssko0** [lilidream/Chinese_GShade#1]
首先非常抱歉，我还不太会使用github，如果在错误的地方进行反馈了请您删除这一条。
在最近使用的过程中出现了所有的ADOF和Deband标黄错误提示，我一开始尝试调整了文件夹内的数值，但似乎没有作用，我不知道是在哪一个环节出了问题，gshade本体和中文模块也全部删除重装过一次，问题似乎还在
![QQ截图20220505121102](https://user-images.githubusercontent.com/104961380/166863164-e97d5d65-2f0c-4519-9e16-d9c68f691dd0.jpg)
![QQ截图20220505121915](https://user-images.githubusercontent.com/104961380/166863167-98db0cbe-f3bb-4663-a95d-14194e1a8036.jpg)
![QQ截图20220505121931](https://user-images.githubusercontent.com/104961380/166863171-34a41d62-e8c1-4a33-b50e-f3db6a880e91.jpg)
如果您能给出解决方式的话就太好了，十分感谢您制作的这款汉化。

**Comment by lilidream** [comment]
有可能是电脑或游戏场景的问题？应该与汉化无关，是滤镜自身引发的问题。我没遇到过。
